### PR TITLE
Knime4

### LINKED ISSUE #6: Incompatible with KNIME version 4
A major release of KNIME Analytics Platform, version 4, is about to be released. 

The 3D-e-Chem KNIME nodes have their KNIME dependencies pinned to >=3.X.0 and <4.0.0 and the nodes use KNIME v3 p2 update sites.

Also since KNIME 3.7 the KNIME SDK was replaced with Eclipse and a KNIME target platform, see https://github.com/knime/knime-sdk-setup

Without a new release of the 3D-e-Chem KNIME nodes and it's 3D-e-Chem dependencies, they will not be install-able in the new KNIME version.

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #6

### CODE REVIEW

**Comment by sverhoeven** [comment]
Tests are failing due KLIFS growth and nullpointer exceptions.

@AJK-dev do you have time to look at the failing tests?

**Comment by AJK-dev** [comment]
I've updated the testflows, which seem to work correctly. 
The only issue is now that instead of failing when performing some faulty requests it now also ends with a java.lang.Exception. Could this be because of the switch from oracle-jdk8 to openjdk8?

**Comment by AJK-dev** [comment]
The KLIFS server was returning some different error messages than initially defined, so either the test definition has been updated and/or the server-side error handling has been adapted. Issues resolved!

**Comment by AJK-dev** [comment]
@sverhoeven: Ready to merge and update to 1.1.2

**Pull request merged**
